services:
  app:
    build: .
    container_name: php-sample
    ports:
      - "8089:80"
    environment:
      DB_HOST: root
      DB_NAME: toko_listrik
      DB_USER: root
      DB_PASS: change_me
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: php-mysql-sample
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toko_listrik
      MYSQL_USER: root
      MYSQL_PASSWORD: change_me
    ports:
      - "3100:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/qry_toko_listrik.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

volumes:
  db_data:
